### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [dqrobotics/python#27]
I’m trying to build Linux AArch64 wheels. The wheels were built successfully but I’m getting the following assertion error on running DQ_test.py: 

https://github.com/odidev/python/runs/4177508116?check_suite_focus=true#step:5:552 

@mmmarinho, Could you please have a look and share your suggestion on the same?

**Comment by mmmarinho** [comment]
@odidev Hello, thank you for the report!

I could replicate the issue and got it fixed (72e781d) and I'll probably get alpha builds deployed to PyPi, however, I'd like to remind you that we do not officially support aarch64.

Thanks again!
