### ISSUE TITLE
[BUG] The `DQ_Kinematics::line_to_line_residual` is not correctly exposed to Python.

### ISSUE THREAD

**Issue by qlin960618** [dqrobotics/python#48]
**************************
### Code of Conduct
_By submitting this report you automatically agree that you've read and accepted the following conditions._ 
- Support for DQ Robotics is given voluntarily and it's not the developers' role to educate and/or convince anyone of their vision.
- Any possible response and its timeliness will be based on the relevance, accuracy, and politeness of a request and the following discussion.
- If a DQ Robotics member replies, the user must let them know if their response solves their issue or not. 
- Any suggestion/advice/request made by anyone, as well intentioned as they might be, might not be incorporated into DQ Robotics.
*************************

~**Bug description**~
~line_to_line_residual  is the DQ_Kinematic was not pesent. Comment seem to reference to line_to_point_residual instead.~

~propose fix maybe in #47~

_Edit by @mmmarinho for clarity:_

# Bug

There is no `line_to_line_residual` accessible through the Python API. 

# Cause

There are two wrappers for `line_to_point_residual` one in L62 and one in L64. Probably it was a typo, and given that `pybind11` doesn't complain about redefined wrappers (at least not in this situation), it has been around for a long time. 

https://github.com/dqrobotics/python/blob/413595ee8c1964a7b960c687c19e4f9603d17c35/src/robot_modeling/DQ_Kinematics_py.cpp#L62

https://github.com/dqrobotics/python/blob/413595ee8c1964a7b960c687c19e4f9603d17c35/src/robot_modeling/DQ_Kinematics_py.cpp#L64

# Fix

See #47

**Comment by mmmarinho** [comment]
@qlin960618 Thanks, if the CI passes you can check the new ‘—pre’ version and it should be working.
