### ISSUE TITLE
[BUG] cross(a,b) function is available in Matlab but isn't in Python

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/python#7]
**Bug description**
Hi @mmmarinho !
- The cross(a,b) and dot(a,b) functions are available in Matlab but isn't in Python.

*Code*
This minimal example works on Matlab:
```
cross(DQ([0 1 0 0]), DQ([0 0 1 0]) )
```
*Output*
```
ans = 
         1k
```

**Expected behavior**
- I expect the same functionalities for Matlab and Python. For instance, 
```
from dqrobotics import *
cross(DQ([0,1,0,0,]), DQ([0,0,1,0]))
```
*Expected output*
```
0 0i 0j 1k +E( 0 0i 0j 0k )
```

**Environment:**
 - OS: [Ubuntu 18.04]
 - dqrobotics version 0.1.1.20
 - Python version [Python 3.6.7 ]
 - MATLAB version [R2016b]

Cheers, 

Juancho

**Comment by mmmarinho** [comment]
Hello, @juanjqo,

Good catch. Should be working now.
