### ISSUE TITLE
line-to-line angle function [QUESTION]

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/python#9]
Hi @mmmarinho, 

There is no a function (to my best knowledge) to compute the angle between two lines in Python.
(Using, for instance, the Eq. 35 of Marinho et al. (2019))
This is:

```
line1 = k_ + E_*cross(0 , k_);
line2 = i_ + E_*cross(0 , i_);
angle = DQ_Geometry.line_to_line_angle(line1, line2)
```

> angle =
> 
> 1.570796326794897

Could you add this feature (if feasible)?

Cheers,

Juancho

**Comment by mmmarinho** [comment]
Hello, @juanjqo 

It's added. Let me know if it doesn't work well.

**Comment by juanjqo** [comment]
@mmmarinho 
Thanks!
